from reportlab.lib.pagesizes import letter
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)

from reportlab.lib.styles import getSampleStyleSheet
from datetime import datetime



def generate_pdf(data):

    filename = "reports/Risk_Intelligence_Report.pdf"


    pdf = SimpleDocTemplate(
        filename,
        pagesize=letter
    )


    styles = getSampleStyleSheet()


    content = []


    # Title

    content.append(
        Paragraph(
            "AI Multi-Risk Intelligence System",
            styles["Title"]
        )
    )


    content.append(
        Spacer(1,20)
    )


    # Report Information

    report_info = f"""

    <b>Report Type:</b> AI Risk Analysis Report<br/>

    <b>Generated Date:</b>
    {datetime.now().strftime('%d-%m-%Y %H:%M')}<br/>

    <b>Total Predictions:</b>
    {data.get('total_risks',0)}

    """


    content.append(
        Paragraph(
            report_info,
            styles["Normal"]
        )
    )


    content.append(
        Spacer(1,20)
    )



    # Risk Details


    for risk in data.get("results",[]):


        score = risk.get(
            "score",
            risk.get("risk_score",0)
        )


        status = risk.get(
            "status",
            "Unknown"
        )


        recommendation = risk.get(
            "recommendation",
            "Monitor risk regularly"
        )


        report = f"""

        <b>Risk Category:</b>
        {risk.get('risk_type')}<br/><br/>


        <b>AI Prediction Score:</b>
        {score}%<br/><br/>


        <b>Risk Level:</b>
        {status}<br/><br/>


        <b>Analysis:</b><br/>

{risk.get(
'explanation',
'AI detected risk pattern'
)}

<br/><br/>


        <b>Recommendation:</b><br/>

        {recommendation}

        """


        content.append(
            Paragraph(
                report,
                styles["Normal"]
            )
        )


        content.append(
            Spacer(1,25)
        )



    # Footer note

    content.append(

        Paragraph(

            """
            <b>Note:</b>
            This report is generated by AI Multi-Risk Intelligence System.
            It helps in risk analysis and decision support.
            """,

            styles["Normal"]

        )

    )


    pdf.build(content)


    return filename